### ISSUE TITLE
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'split'

### ISSUE THREAD

**Issue by ShaifAslam** [sebaubuntu-python/aospdtgen#23]
Android device tree generator
Version 0.1.0

[INFO] Parsing all_files.txt
[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/red/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/red/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/red/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 43, in __init__
    self.partitions = Partitions(self.path)
  File "/home/red/.local/lib/python3.10/site-packages/aospdtgen/utils/partitions.py", line 35, in __init__
    self.partitions[PartitionModel.VENDOR] = AndroidPartition(PartitionModel.VENDOR, vendor, self.dump_path)
  File "/home/red/.local/lib/python3.10/site-packages/aospdtgen/utils/partition.py", line 119, in __init__
    self.manifest.import_file(manifest_path)
  File "/home/red/.local/lib/python3.10/site-packages/sebaubuntu_libs/libvintf/manifest.py", line 73, in import_file
    self.entries.append(AidlHal.from_entry(entry))
  File "/home/red/.local/lib/python3.10/site-packages/sebaubuntu_libs/libvintf/aidl.py", line 67, in from_entry
    interfaces = set([AidlInterface.from_fqname(interface)
  File "/home/red/.local/lib/python3.10/site-packages/sebaubuntu_libs/libvintf/aidl.py", line 67, in <listcomp>
    interfaces = set([AidlInterface.from_fqname(interface)
  File "/home/red/.local/lib/python3.10/site-packages/sebaubuntu_libs/libvintf/aidl.py", line 40, in from_fqname
    name, instance = string.split("/", 1)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'split'

**Comment by SebaUbuntu** [comment]
Mind sending a link to download this device firmware?

**Comment by edward0181** [comment]
https://github.com/RandomPush/samsung_a13ve_dump

This has this issue

**Comment by NRanjan-17** [comment]
Android device tree generator
Version 0.1.0

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "I:\aospdtgen\aospdtgen\__main__.py", line 11, in <module>
    main()
  File "I:\aospdtgen\aospdtgen\main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\aospdtgen\aospdtgen\device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "I:\Users\Nalinish\AppData\Local\Programs\Python\Python311\Lib\site-packages\sebaubuntu_libs\libandroid\partitions\partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by edward0181** [comment]
Latest FW on Samsung A13ve still same issue

## a13vensxx-user 13 TP1A.220624.014 A137FXXS1BWA2 release-keys
- Manufacturer: samsung
- Platform: mt6768
- Codename: a13ve
- Brand: samsung
- Flavor: a13vensxx-user
- Release Version: 13
- Kernel Version: 4.19.191
- Id: TP1A.220624.014
- Incremental: A137FXXS1BWA2
- Tags: release-keys
- CPU Abilist: armeabi-v7a,armeabi
- A/B Device: false
- Locale: en-GB
- Screen Density: undefined
- Fingerprint: samsung/a13vensxx/a13ve:12/SP1A.210812.016/A137FXXS1BWA2:user/release-keys
- OTA version:
- Branch: a13vensxx-user-13-TP1A.220624.014-A137FXXS1BWA2-release-keys
- Repo: samsung_a13ve_dump
TWRP device tree generator
Version 3.0.0

[INFO] Cloning AIK...

Done! You can find the device tree in twrp-device-tree/samsung/a13ve
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1241  100  1241    0     0   3841      0 --:--:-- --:--:-- --:--:--  3842
Android device tree generator
Version 0.1.0

[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/usr/local/lib/python3.10/dist-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 36, in __init__
    self.partitions[PartitionModel.VENDOR] = AndroidPartition(PartitionModel.VENDOR, vendor)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 56, in __init__
    self.manifest.import_file(manifest_path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/vintf/manifest.py", line 74, in import_file
    self.entries.append(AidlHal.from_entry(entry))
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/vintf/aidl.py", line 68, in from_entry
    interfaces = set([AidlInterface.from_fqname(interface)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/vintf/aidl.py", line 68, in <listcomp>
    interfaces = set([AidlInterface.from_fqname(interface)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/vintf/aidl.py", line 41, in from_fqname
    name, instance = string.split("/", 1)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'split'
