### ISSUE TITLE
assert PartitionModel.SYSTEM in self.partitions

### ISSUE THREAD

**Issue by ghost** [sebaubuntu-python/aospdtgen#27]
`PS C:\Users\x\Desktop> python -m aospdtgen -o C:\Users\x\Desktop\rom C:\Users\x\Desktop\images
Android device tree generator
Version 0.1.0

[INFO] Parsing all_files.txt
[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\aospdtgen\__main__.py", line 11, in <module>
    main()
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\aospdtgen\main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\aospdtgen\device_tree.py", line 43, in __init__
    self.partitions = Partitions(self.path)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\aospdtgen\utils\partitions.py", line 26, in __init__
    assert PartitionModel.SYSTEM in self.partitions
AssertionError`

i try in wsl&windows,dont work.
model： realme q3
kernel-souce: https://github.com/realme-kernel-opensource/realmeQ3_Q3pro_AndroidS_kernel-source
vendor-source: https://github.com/realme-kernel-opensource/realmeQ3_Q3pro_AndroidS_vendor-source

**Comment by n0raml** [comment]
img url: https://drive.google.com/file/d/1WaLA-ICjv4dRuaUx-txt2L7d_NOKzUXG/view?usp=sharing

**Comment by Poempoat** [comment]
You must use dumpyara.

**Comment by AidanWarner97** [comment]
> You must use dumpyara.

I am coming across the same issue and I can assure you I used dumpyara

**Comment by SebaUbuntu** [comment]
Account gone, anyway, looks like this user didn't dump the images
