### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' [Sony stock firmware (pdx-201)]

### ISSUE THREAD

**Issue by KingProNoob2** [sebaubuntu-python/aospdtgen#36]
Android device tree generator
Version 0.1.0

[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
[INFO] Parsing build props and device info
[INFO] Parsing fstab
[INFO] Extracting boot image
[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/erik/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/erik/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/erik/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 62, in __init__
    self.boot_configuration = BootConfiguration(self.path)
  File "/home/erik/.local/lib/python3.10/site-packages/aospdtgen/utils/boot_configuration.py", line 26, in __init__
    self.boot_image_info = self.boot_aik_manager.unpackimg(self.boot)
  File "/home/erik/.local/lib/python3.10/site-packages/sebaubuntu_libs/libaik/__init__.py", line 109, in unpackimg
    image_prefix = image.name

**Comment by KingProNoob2** [comment]
Will send firmware soon

**Comment by SebaUbuntu** [comment]
"Soon" in Earth time or Venus time?

**Comment by SebaUbuntu** [comment]
Closing for inactivity
