### ISSUE TITLE
assert PartitionModel.SYSTEM in self.partitions AssertionError

### ISSUE THREAD

**Issue by Carckv2** [sebaubuntu-python/aospdtgen#40]
aospdtgen$ python3 -m aospdtgen  '/home/ninja/Desktop/working' 
Android device tree generator
Version 0.1.0

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ninja/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/ninja/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/ninja/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
AssertionError

**Comment by SebaUbuntu** [comment]
Needs a dump link

**Comment by madhuraj0** [comment]
@Carckv2 were you able to fix this error?

**Comment by SebaUbuntu** [comment]
Closing for inactivity and not related to dumpyara

**Comment by shyambandla** [comment]
for me . i have a super.img in .tar for (.tar.md5 works too). 

1. first download otatools
2.  lz4 -d super.img.lz4 super.img
3.  tar cvf super.tar super.img
4.  now python -m dumpyara -o ~/output super.tar

this worked for me

**Comment by baizhi958216** [comment]
> for me . i have a super.img in .tar for (.tar.md5 works too).
> 
> 1. first download otatools
> 2. lz4 -d super.img.lz4 super.img
> 3. tar cvf super.tar super.img
> 4. now python -m dumpyara -o ~/output super.tar
> 
> this worked for me

Don`t forgot install `cpio` package :P
