### ISSUE TITLE
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2

### ISSUE THREAD

**Issue by a0193143** [sebaubuntu-python/aospdtgen#44]
```
Android device tree generator
Version 1.0.0

[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/build/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/build/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/build/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/home/build/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 36, in __init__
    self.partitions[PartitionModel.VENDOR] = AndroidPartition(PartitionModel.VENDOR, vendor)
  File "/home/build/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 56, in __init__
    self.manifest.import_file(manifest_path)
  File "/home/build/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/vintf/manifest.py", line 57, in import_file
    tree = ElementTree.parse(file)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2
```

Firmware [here](https://dlcdnets.asus.com/pub/ASUS/ZenFone/ZB601KL/UL-ASUS_X00T-WW-16.2017.2009.087-user.zip?model=ZenFone%20Max%20Pro(M1)(ZB602KL)) if nedded

**Comment by SebaUbuntu** [comment]
Send dump or firmware link
