### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' (pdx203)

### ISSUE THREAD

**Issue by TechnoHT** [sebaubuntu-python/aospdtgen#45]
Getting this error when generating from dumped dynamic partitions (hence I also don't know if I need to put something else there)

```Android device tree generator
Version 1.0.0

[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
[INFO] Parsing build props and device info
[INFO] Parsing fstab
[INFO] Extracting boot image
[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ryliea/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/ryliea/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/ryliea/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 62, in __init__
    self.boot_configuration = BootConfiguration(self.path)
  File "/home/ryliea/.local/lib/python3.10/site-packages/aospdtgen/utils/boot_configuration.py", line 26, in __init__
    self.boot_image_info = self.boot_aik_manager.unpackimg(self.boot)
  File "/home/ryliea/.local/lib/python3.10/site-packages/sebaubuntu_libs/libaik/__init__.py", line 109, in unpackimg
    image_prefix = image.name
AttributeError: 'NoneType' object has no attribute 'name'```

Original firmware : [58.2.C.5.2](https://tennox-my.sharepoint.com/:u:/g/personal/tennox_tennox_onmicrosoft_com/ES8RMw4lp2dAo48lM-PbIe8BehXtjVjPYHdVXicWXjx5eQ?e=JlDqbb/)
Extracted Super.img : [super_x-FLASH-ALL-2389.img](https://tennox-my.sharepoint.com/:u:/g/personal/tennox_tennox_onmicrosoft_com/EQq0gm_9L7lFvhKCdAG2aXwBj3UeOk3BDJ06d7cH_1-Qhg?e=R4K655)
Dumped Super.tar : [super_dumped.tar](https://tennox-my.sharepoint.com/:u:/g/personal/tennox_tennox_onmicrosoft_com/EQDFLQEnxAhMkJSckwBAEz8BUg1QlWh_rj7UgQsVKk55UQ?e=NDNkBK)
Boot image : [Boot.img](https://tennox-my.sharepoint.com/:u:/g/personal/tennox_tennox_onmicrosoft_com/EZANgFIKeh1Lut3wP3SJJYQBvhQ36mU89lgslNHdKEemfg?e=qQK7c7) ( I don't know what procedure I have to make with it nor where to put it in working directory )

**Comment by TechnoHT** [comment]
This is my dumpyara log : 
```
python3 -m dumpyara super.tar                                                             ✔ 
Dumpyara
Version 1.0.1

[INFO] Step 1 - Extracting archive
[INFO] Step 2 - Preparing partition images
[INFO] Pattern *payload.bin* not found
[INFO] Found multipartition image: super_X-FLASH-ALL-2389.img
[INFO] Failed to unsparse super_X-FLASH-ALL-2389.img
[INFO] correct_ab_filenames: file: /home/ryliea/tree/super/temp_raw_images/vendor_a.img, file_stem: vendor_a
[INFO] correct_ab_filenames: file: /home/ryliea/tree/super/temp_raw_images/odm_b.img, file_stem: odm_b
[INFO] correct_ab_filenames: file: /home/ryliea/tree/super/temp_raw_images/system_b.img, file_stem: system_b
[INFO] correct_ab_filenames: file: /home/ryliea/tree/super/temp_raw_images/vendor_b.img, file_stem: vendor_b
[INFO] correct_ab_filenames: /home/ryliea/tree/super/temp_raw_images/vendor.img already exists, skipping
[INFO] correct_ab_filenames: file: /home/ryliea/tree/super/temp_raw_images/product_b.img, file_stem: product_b
[INFO] Step 3 - Extracting partitions
[INFO] Extracting odm
[INFO] Extracting product
[INFO] Extracting system
[INFO] Extracting vendor
[INFO] Step 4 - Finalizing
[INFO] Creating all_files.txt

Done! You can find the dump in /home/ryliea/tree/super
```
