### ISSUE TITLE
Im using it for devicecodename "marble"

### ISSUE THREAD

**Issue by SharmagRit** [sebaubuntu-python/aospdtgen#50]
Yeah it's my 1st time so don't know im doing in right way or not, so pls tell. After command im getting this error: sharmagrit@SharmagRit:~/aospdtgen$ python3 -m aospdtgen /home/sharmagrit/miui_MARBLE_V14.0.19.0.TMRCNXM_cdffc8d82e_13.0/
Android device tree generator
Version 1.0.0

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sharmagrit/aospdtgen/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/sharmagrit/aospdtgen/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/sharmagrit/aospdtgen/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/home/sharmagrit/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
AssertionError

**Comment by King12689** [comment]
same error

**Comment by realThingss** [comment]
Same

**Comment by ghazzor** [comment]
same
