### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Iascker** [sebaubuntu-python/aospdtgen#51]
Android device tree generator
Version 1.0.0

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aos/AndroidTools/aospdtgen/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/aos/AndroidTools/aospdtgen/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/aos/AndroidTools/aospdtgen/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 25, in __init__
    self.partitions[PartitionModel.SYSTEM] = AndroidPartition(PartitionModel.SYSTEM, system)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 38, in __init__
    self.files = get_files_list(self.path)
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 29, in get_files_list
    files.extend(get_files_list(i))
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/dist-packages/sebaubuntu_libs/libandroid/partitions/partition.py", line 25, in get_files_list
    for i in path.iterdir():
  File "/usr/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/aos/AndroidTools/DumprX/out/system/system/priv-app/BuiltInPrintService/lib/arm64/libwfds.so'

ROM: lisa_global_images_V14.0.3.0.TKOMIXM_20230324.0000.00_13.0_global_b96438c491.tgz

**Comment by Iascker** [comment]
* It worked for me
https://github.com/sebaubuntu-python/sebaubuntu_libs/pull/11/commits/f3a0042c84b1a97ad7cd0be2f2ca19fba18deee6
