### ISSUE TITLE
[V1.0.1] Fails to build tree from recovery .img same as #50

### ISSUE THREAD

**Issue by ghazzor** [sebaubuntu-python/aospdtgen#62]
same as #50 
Android device tree generator
Version 1.0.1

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kartik/.local/lib/python3.10/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/kartik/.local/lib/python3.10/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
  File "/home/kartik/.local/lib/python3.10/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
  File "/home/kartik/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
AssertionError

**Comment by SebaUbuntu** [comment]
You're probably doing it wrong, it's not finding a system build.prop

**Comment by ghazzor** [comment]
> You're probably doing it wrong, it's not finding a system build.prop
my recovery.img is in $HOME/android/twrp
well i used this command
```
cd $HOME/android/twrp
python3 -m aospdtgen recovery.img 
```

**Comment by SebaUbuntu** [comment]
Yes you need a full dump, as stated literally everywhere in the readme
