### ISSUE TITLE
AssertionError when Running aospdtgen on MIUI Dump

### ISSUE THREAD

**Issue by RuslanYestemessov** [sebaubuntu-python/aospdtgen#69]
**Operating System**: Ubuntu 23.04
**Python Version**: 3.10
**aospdtgen Version**: 1.1.1

I encountered an AssertionError when attempting to generate an Android device tree using aospdtgen with a MIUI dump from the ZIYIGlobal variant. This error occurs during the initial phase where the tool tries to figure out the partition scheme.

```Android device tree generator
Version 1.1.1

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
...
File "/home/ruslan/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
AssertionError
```

I would appreciate any guidance on resolving this issue or any workarounds available. Thank you!

PS: Firmware OTA file [here](**url**)

**Comment by vedxp** [comment]
Encountering the same:

```sh
python3 -m aospdtgen /working/export84276185
$ Android device tree generator
Version 1.1.1

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by Minionguyjpro** [comment]
Whoops, think I found the issue. We shouldn't use the boot image. Instead we should use the dumpyara image as we said.
