### ISSUE TITLE
AssertionError: No fstab found

### ISSUE THREAD

**Issue by Minionguyjpro** [sebaubuntu-python/aospdtgen#77]
Hello, I am getting this error after using dumpyara to dump my OTA package and then parse it to aospdtgen:
```
Android device tree generator
Version 1.1.1

[INFO] Figuring out partitions scheme
[WARNING] Unknown HAL type native
[INFO] Parsing build props and device info
[INFO] Parsing fstab
Traceback (most recent call last):
  File "/home/minionguyjpro/.local/bin/aospdtgen", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/minionguyjpro/.local/lib/python3.12/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minionguyjpro/.local/lib/python3.12/site-packages/aospdtgen/device_tree.py", line 53, in __init__
    assert fstabs, "No fstab found"
           ^^^^^^
AssertionError: No fstab found
```
The path is valid, although I don't see a seperate fstab although I do see them in the ramdisks but it's called ``fstab.samsungexynos7870`` (referring to my SoC). Maybe renaming to fstab would work?

**Comment by Minionguyjpro** [comment]
Found a recovery.fstab which is also pointed to in the all_files.txt file, not sure why aospdtgen cannot find it.

**Comment by Igorpetinik** [comment]
I can try create pull request with using ALL fstab files. just wait.

**Comment by Igorpetinik** [comment]
oops, i can't

**Comment by rosbeef** [comment]
> not sure why aospdtgen cannot find it

maybe because script search for file starting with fstab. not ending with .fstab ?

`if (is_relative_to(file.relative_to(self.vendor.path), "etc")
                        and file.name.startswith("fstab."))
`

**Comment by magnoliy** [comment]
got the same issue. i have fstab.samsungexynos7570, recovery.fstab and another fstab.samsungexynos7570 in my dumpyara dump. has anyone fixed it? or is the dump folder not correctly setup?

**Comment by magnoliy** [comment]
fixed it by copying the fstab.____ from /boot/ramdisk to /system/vendor/etc

**Comment by Minionguyjpro** [comment]
> fixed it by copying the fstab.____ from /boot/ramdisk to /system/vendor/etc

Worked! I copied it to ``system/etc`` though, which also worked.

**Comment by wwaaafa** [comment]
> 通过将 fstab.____ 从 /boot/ramdisk 复制到 /system/vendor/etc 来修复此问题

/vendor/etc is also working
/vendor/etc同样有效
