### ISSUE TITLE
Traceback (most recent call last):   File "<frozen runpy>", line 198, in _run_module_as_main   File "<frozen runpy>", line 88, in _run_code   File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/__main__.py", line 11, in <module>     main()   File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/main.py", line 31, in main     dump = DeviceTree(args.dump_path)            ^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/device_tree.py", line 36, in __init__     self.partitions = Partitions(self.path)                       ^^^^^^^^^^^^^^^^^^^^^   File "/home/nokeew/.local/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__     assert PartitionModel.SYSTEM in self.partitions

### ISSUE THREAD

**Issue by Nokeew** [sebaubuntu-python/aospdtgen#79]
Hello there, i were trying to use the aospdtgen but i get this error:
nokeew@HOME-PC:~$ python3 -m aospdtgen \\wsl.localhost\Ubuntu\tmp\rmx3710
Android device tree generator
Version 1.1.1

[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nokeew/.local/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by SebaUbuntu** [comment]
Your dump wasn't made with https://github.com/SebaUbuntu/dumpyara
