### ISSUE TITLE
 assert PartitionModel.SYSTEM in self.partitions AssertionError

### ISSUE THREAD

**Issue by Nokeew** [sebaubuntu-python/aospdtgen#80]
[INFO] Figuring out partitions scheme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/main.py", line 31, in main
    dump = DeviceTree(args.dump_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nokeew/.local/lib/python3.12/site-packages/aospdtgen/device_tree.py", line 36, in __init__
    self.partitions = Partitions(self.path)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nokeew/.local/lib/python3.12/site-packages/sebaubuntu_libs/libandroid/partitions/partitions.py", line 27, in __init__
    assert PartitionModel.SYSTEM in self.partitions
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
dump made by dumpyara

**Comment by Nokeew** [comment]
im writing the path to the dump 
python3 -m aospdtgen ~home/nokeew/tree 
maybe it is wrong?

**Comment by NikitaSavc** [comment]
Same.
@SebaUbuntu

**Comment by fspkwon** [comment]
yeah im getting the same thing what gives? if we can extract the image, and repack it with the image kitchen we used why cant we specify the specific directories or that its not asking you to do that already as the program

**Comment by SebaUbuntu** [comment]
If the dump was successful then you are providing the wrong path to aospdtgen
